apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: omsorgspenger-oidc-auth-proxy
  namespace: omsorgspenger
  labels:
    team: omsorgspenger
spec:
  image: {{oidcAuthProxyImage}}
  port: 8080
  azure:
    application:
      enabled: true
      tenant: {{azureTenant}}
      replyURLs:
        - {{oidcAuthProxyCallbackUrl}}
  accessPolicy:
    outbound:
      external:
        - host: login.microsoftonline.com
      rules:
        - application: omsorgspenger-oidc-auth-proxy-redis
        - application: omsorgspenger-sak
        - application: omsorgspenger-rammemeldinger
  liveness:
    path: isalive
    initialDelay: 20
    timeout: 1
    periodSeconds: 5
    failureThreshold: 10
  readiness:
    path: isready
    initialDelay: 20
    timeout: 1
  resources:
    limits:
      cpu: 500m
      memory: 512Mi
    requests:
      cpu: 200m
      memory: 256Mi
  ingresses:
  {{#each ingresses as |url|}}
     - {{url}}
  {{/each}}
  replicas:
    min: {{minReplicas}}
    max: {{maxReplicas}}
    cpuThresholdPercentage: 90
  prometheus:
    enabled: false
    path: /metrics
  filesFrom:
    - secret: omsorgspenger-oidc-auth-proxy-cookie-secrets
      mountPath: /var/run/secrets/cookie
    - secret: omsorgspenger-oidc-auth-proxy-redis-password
      mountPath: /var/run/secrets/redis
  env:
  {{#each env}}
    - name: {{@key}}
      value: {{this}}
  {{/each}}
    - name: PROXY_CONFIG
      value: 'value:{"apis":[{"path":"sak","scopes":"{{omsorgspengerSakScopes}}","url":"http://omsorgspenger-sak.omsorgspenger.svc.cluster.local"},{"path":"rammemeldinger","scopes":"{{omsorgspengerRammemeldingerScopes}}","url":"http://omsorgspenger-rammemeldinger.omsorgspenger.svc.cluster.local"}]}'
    - name: REDIS_HOST
      value: value:omsorgspenger-oidc-auth-proxy-redis.omsorgspenger.svc.cluster.local
    - name: REDIS_PORT
      value: value:6379
    - name: SESSION_ID_COOKIE_NAME
      value: value:omsorgspenger
    - name: CORS_ALLOWED_HEADERS
      value: value:Content-Type,Referer,X-Request-ID
    - name: CORS_EXPOSED_HEADERS
      value: value:Location
    - name: CLIENT_ID
      value: env:AZURE_APP_CLIENT_ID
    - name: DISCOVERY_URL
      value: env:AZURE_APP_WELL_KNOWN_URL
    - name: JWK
      value: path:/var/run/secrets/nais.io/azure/AZURE_APP_JWK
    - name: REDIS_PASSWORD
      value: path:/var/run/secrets/redis/REDIS_PASSWORD
    - name: SESSION_ID_COOKIE_SIGN_SECRET
      value: path:/var/run/secrets/cookie/SESSION_ID_COOKIE_SIGN_SECRET
    - name: SESSION_ID_COOKIE_VERIFY_SECRET
      value: path:/var/run/secrets/cookie/SESSION_ID_COOKIE_VERIFY_SECRET
