apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: omsorgspenger-oidc-auth-proxy-redis
  namespace: omsorgspenger
  labels:
    team: omsorgspenger
spec:
  image: bitnami/redis:6.2.5
  port: 6379
  replicas: # A single Redis-app doesn't scale
    min: 1
    max: 1 # More replicas doesn't sync
  resources: # you need to monitor the resource usage yourself
    limits:
      cpu: 200m
      memory: 256Mi
    requests:
      cpu: 100m
      memory: 128Mi
  service:
    port: 6379
    protocol: redis
  accessPolicy: # for GCP
    inbound:
      rules:
        - application: omsorgspenger-oidc-auth-proxy
  envFrom:
    - secret: omsorgspenger-oidc-auth-proxy-redis-password
