name: omsorgspenger-oidc-auth-proxy DEV
on:
  push:
    paths:
      - 'nais/naiserator.yaml'
      - 'nais/dev-gcp.json'
    branches:
      - main

jobs:
  deploy-dev:
    name: deploy DEV
    runs-on: ubuntu-latest
    steps:
      - name: Hente kode
        uses: actions/checkout@v2
      - name: Deploy dev-gcp
        uses: nais/deploy/actions/deploy@v1
        env:
          APIKEY: ${{ secrets.NAIS_DEPLOY_APIKEY }}
          CLUSTER: dev-gcp
          RESOURCE: nais/naiserator.yaml
          VARS: nais/dev-gcp.json
          PRINT_PAYLOAD: true
