name: omsorgspenger-oidc-auth-proxy-redis
on:
  push:
    paths:
      - 'nais/redis.yaml'

jobs:
  deploy:
    name: deploy redis
    runs-on: ubuntu-latest
    steps:
      - name: Hente kode
        uses: actions/checkout@v2
      - name: Deploy dev-gcp
        uses: nais/deploy/actions/deploy@v1
        env:
          APIKEY: ${{ secrets.NAIS_DEPLOY_APIKEY }}
          CLUSTER: dev-gcp
          RESOURCE: nais/redis.yaml
          PRINT_PAYLOAD: true
      - name: Deploy prod-gcp
        if: github.ref == 'refs/heads/main'
        uses: nais/deploy/actions/deploy@v1
        env:
          APIKEY: ${{ secrets.NAIS_DEPLOY_APIKEY }}
          CLUSTER: prod-gcp
          RESOURCE: nais/redis.yaml
          PRINT_PAYLOAD: true